# Generated by Django 5.1.1 on 2024-09-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("children", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=30)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=30)),
                ("email", models.CharField(blank=True, max_length=32)),
                ("phone_number", models.CharField(blank=True, max_length=16)),
                ("creation_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_creators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_updators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
